name: madaresco
description: A new Flutter application.

publish_to: 'none'
version: 4.4.8+67
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  http: ^0.13.6
  fluttertoast: ^8.2.1
  modal_progress_hud_nsn: ^0.4.0
  url_launcher: ^6.1.11
  logging: ^1.1.1
  get_it: ^7.3.0
  # Bloc for state management
  flutter_bloc: ^8.1.2
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  google_fonts: ^4.0.4
  badges: ^3.1.1
  dio: ^5.1.2
  progress_dialog_null_safe: ^1.0.7
  carousel_slider: ^4.2.1
  preload_page_view: ^0.2.0
  expandable: ^5.0.1
  pusher_client: ^2.0.0
  record: ^4.4.4
#  multi_image_picker: ^4.8.1
  flutter_html: ^3.0.0-beta.1
  flutter_staggered_grid_view:
  email_validator: ^2.1.17
  maps_launcher: ^2.2.0
  audioplayers: 0.20.1
  firebase_core: ^2.10.0 #don't change # Support android & ios 
  firebase_messaging: ^14.4.1 # Support android & ios
#  firebase_analytics:
  flutter_local_notifications: ^9.5.3+1 #don't change # Support android & ios with known Issues
  image_picker: ^0.8.7+5
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  lottie: ^2.3.2
  google_maps_flutter: ^2.2.6
  path_provider: ^2.0.15
  # media_store: ^1.0.0
  youtube_player_flutter: ^8.1.2
  dropdown_search: ^5.0.6
  gr_zoom: ^1.0.0+2
  file_picker:
  chewie: ^1.5.0 #don't change
  queen_validators: ^1.0.1
  device_info: ^2.0.3
  flutter_spinkit: ^5.2.0
  photo_view: ^0.14.0
  flutter_downloader: ^1.10.2
  #open_file: ^3.3.1 
  open_filex: ^4.3.2
  flutter_html_to_pdf:
  multi_image_picker_plus: ^0.0.3
  firebase_analytics: ^10.4.5
  flutter_hooks: ^0.20.0
  async: ^2.11.0




dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter




flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/lang/ku.json
    - assets/lotti/
    - assets/
    - assets/lang/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
